name: KtoxzWebhook
main: dev.ktoxz.webhooksender.WebhookSender
version: 1.1
api-version: 1.20
author: ktoxz
commands:
  setcentralchest:
    description: Đặt vị trí rương trung tâm
    usage: /setcentralchest
    permission: webhook.setchest