name: KtoxzWebhook
main: dev.ktoxz.main.KtoxzWebhook
version: 1.2
api-version: 1.20
author: ktoxz
commands:
  setcentralchest:
    description: Đặt vị trí rương trung tâm
    usage: /setcentralchest
    permission: webhook.setchest