name: KtoxzPlugin
main: dev.ktoxz.main.KtoxzWebhook
version: 1.2.6
api-version: 1.20
author: ktoxz

commands:
  setcentralchest:
    description: Đặt vị trí rương trung tâm
    usage: /setcentralchest
    permission: ktoxz.setcentralchest
    permission-message: Bạn không có quyền sử dụng lệnh này!

  tp:
    description: Teleport đến địa điểm đã định trước
    permission: ktoxz.tp
    usage: /tp <spawn|home|minigame|name>

  addspot:
    description: Thêm vị trí
    usage: /addspot <name>
    permission: ktoxz.addspot
    permission-message: Bạn không có quyền sử dụng lệnh này!

  balance:
    description: Xem số dư còn lại
    usage: /balance

  givebalance:
    description: Gửi tiền cho người khác
    usage: /givebalance <name> <sodu>
    permission: ktoxz.givebalance
    permission-message: Bạn không có quyền sử dụng lệnh này!

  pay:
    description: Trả tiền cho người khác
    usage: /pay <name> <amount>

  ac:
    description: Đồng ý nhận tiền từ người khác
    usage: /ac <name> <amount>

  link:
    description: Liên kết tài khoản với Discord
    usage: /link <tên discord>

  dual:
    description: Tạo phòng hoặc rủ ai vô đấm
    usage: /dual [name...] [include_self (true | false)]

  join:
    description: Tham gia vào phòng đấm lộn
    usage: /join

  start:
    description: Bắt đầu trận chiến
    usage: /start

  cancel:
    description: Hủy trận
    usage: /cancel

  addArena:
    description: Thêm tên WorldGuard region của arena
    usage: /addArena <region_name>
    permission: ktoxz.addArena
    permission-message: Bạn không có quyền sử dụng lệnh này!

  addArenaSpot:
    description: Thêm chỗ trong arena
    usage: /addArenaSpot <name>
    permission: ktoxz.addArenaSpot
    permission-message: Bạn không có quyền sử dụng lệnh này!

permissions:
  ktoxz.setcentralchest:
    description: Cho phép đặt rương trung tâm
    default: op

  ktoxz.addspot:
    description: Cho phép thêm vị trí mới
    default: op

  ktoxz.givebalance:
    description: Cho phép gửi tiền cho người khác
    default: op

  ktoxz.addArena:
    description: Abc
    default: op

  ktoxz.addArenaSpot:
    description: Abcd
    default: op

  ktoxz.tp:
    description: quyền teleport
    default: true